### ISSUE TITLE
Boolean search properties should be nullable, rather than "not set"

### ISSUE THREAD

**Issue by myrobotzone** [aglasencnik/RadioBrowserWrapper#2]
To start with, a big thanks for the great library.

**Describe the Bug**  
_SearchStationsAsync()_ does not return the stations that one observes using the browser (e.g. _/json/stations/search?name=brian&limit=3_)

**To Reproduce**  
1. Using the browser, navigate to '..../json/stations/search?name=brian&limit=3'
2. Using code that calls RadioBrowserWrapper (e.g. from a test), execute the following:

```csharp
var searchOptions = new AdvancedStationSearchOptions
{
    Name = "brian",
    Limit = 3
};

var stations = await _client.SearchStationsAsync(searchOptions: searchOptions);`
```
3. Observe that step 1 returns three stations, whereas step 2 returns zero stations

**Expected Behavior**  
_SearchStationsAsync()_ returns the same number of stations

**Screenshots**  

Copied form the [spec](https://de1.api.radio-browser.info/):
![image](https://github.com/user-attachments/assets/54dd40c4-267a-4d29-bd82-0cf3d32568d2)
![image](https://github.com/user-attachments/assets/66795722-0660-4f03-91a5-b27af0167b07)

Given the above spec, we see that the following properties are optional (and therefore should be nullable):
* has_geo_info
* has_extended_info
* is_https

However, the code below will serialize it as either true, false, or 'not set':
```csharp
namespace RadioBrowserWrapper.Enums
{
    /// <summary>
    /// Represents the information about a station.
    /// </summary>
    public enum StationInfo
    {
        [EnumMemberValue("not set")]
        NotSet,

        [EnumMemberValue("true")]
        True,

        [EnumMemberValue("false")]
        False
    }
}
```
**Development Environment:**  
- **RadioBrowserWrapper Version**: 1.0.0

**Additional Information**

I will create a PR to fix the issue.

**Comment by aglasencnik** [comment]
Thank you for your contribution :)
